export const categorie = {
	element: ["geo", "dendro", "hydro", "anemo", "electro", "cryo", "pyro", "adaptive"],
	weapontype: ["claymore", "sword", "polearm", "catalyst", "bow"],
	gender: ["male", "female"],
	region: ["mondstadt", "liyue", "snezhnaya", "inazuma"],
	rarity: ["1", "2", "3", "4", "5"],
	day: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
	birthday: ["january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"],
	animal: ["birds", "beasts", "fish", "other"],
	enemies: ["Elemental Lifeforms", "Hilichurls", "The Abyss", "Fatui", "Automatons", "Other Human Factions", "Mystical Beasts", "Enemies of Note"],
	materialtype: {
		local_specialty: ["Local Specialty (Mondstadt)", "Local Specialty (Liyue)", "Local Specialty (Inazuma)"],
		character_lvl_up: ["Character Level-Up Material"],
		character_exp: ["Character EXP Material"],
		talent_lvl_up: ["Talent Level-Up Material"],
		weapon_lvl_up: ["Weapon Ascension Material"],
		weapon_exp: ["Weapon Enhancement Material"],
		fishing: ["Bait", "Fishing Rod"],
		wishing_item: ["Wishing Item", "Limited Wishing Item"],
		other: [
			"Fish",
			"System Access",
			"Refinement Material",
			"Cooking Ingredient",
			"Forging Ore",
			"City States Sigil",
			"Food",
			"Material",
			"BEP",
			"Crafted Item",
			"Feature Activation Material",
			"Very Special Item",
			"Increases Friendship",
			"Consumable",
			"Adventure Item",
			"Lantern Rite Material",
			"Forging Blueprint",
			"Common Voucher",
			"Superior Voucher",
			"Common Currency",
			"Special Currency",
			"Dragonspine Material"
		]
	},
}