export const categorie = {
	enemiesType: ['COMMON', 'ELITE', 'BOSS'],
	element: ["geo", "dendro", "hydro", "anemo", "electro", "cryo", "pyro", "adaptive"],
	weapontype: ["claymore", "sword", "polearm", "catalyst", "bow"],
	gender: ["male", "female"],
	region: ["mondstadt", "liyue", "snezhnaya", "inazuma", "sumeru"],
	rarity: ["1", "2", "3", "4", "5"],
	cristal: ['vayuda', 'agnidus', 'vajrada', 'prithiva', 'shivada', 'varunada'],
	day: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
	birthday: ["january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"],
	animal: ["birds", "beasts", "fish", "other"],
	enemies: ["Elemental Lifeforms", "Hilichurls", "The Abyss", "Fatui", "Automatons", "Other Human Factions", "Mystical Beasts", "Enemies of Note"],
	materialtype: {
		local_specialty: ["Local Specialty (Mondstadt)", "Local Specialty (Liyue)", "Local Specialty (Inazuma)", "Local Specialty (Sumeru)"],
		character_lvl_up: ["Character Level-Up Material"],
		character_exp: ["Character EXP Material"],
		talent_lvl_up: ["Talent Level-Up Material", "Talent Level-Up Materials"],
		weapon_lvl_up: ["Weapon Ascension Material"],
		weapon_exp: ["Weapon Enhancement Material"],
		fishing: ["Fish", "Bait", "Fishing Rod"],
		wishing_item: ["Wishing Item", "Limited Wishing Item"],
		currency: ["Common Voucher", "Superior Voucher", "Common Currency", "Special Currency", "City States Sigil"],
		exp: ["System Access", "BEP", "Increases Friendship"],
		forge: ["Forging Ore", "Forging Blueprint"],
		event: ["Adventure Item", "Lantern Rite Material", "Dragonspine Material"],
		payable: ["Feature Activation Material"],
		birthday: ["Very Special Item"],
		consumable: ["Consumable"],
		material: ["Material", "Crafted Item", "Refinement Material"],
		cooking: ["Cooking Ingredient", "food", "fish"],
	},
}